### ISSUE TITLE
Failing to push new tag

### ISSUE THREAD

**Issue by gauntface** [mikeal/merge-release#15]
First off - thank you so much for this action - super helpful and I love it!

Just a minor thing but the tags aren't getting push to my repo, checkout https://github.com/gauntface/hopin-base-theme/runs/418560198 and look at the publish step, it has the following output:

```
/usr/bin/docker run --name dfb440ba89b38624e1eaaa1e1a3e1468a31_9e3140 --label 488dfb --workdir /github/workspace --rm -e GITHUB_TOKEN -e NPM_AUTH_TOKEN -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/hopin-base-theme/hopin-base-theme":"/github/workspace" 488dfb:440ba89b38624e1eaaa1e1a3e1468a31
npx merge-release
npx: installed 68 in 2.884s
v0.0.4
current: 0.0.4
 / version: patch
new version: v0.0.5

npm notice 
+ @hopin/hugo-base-theme@0.0.6
npm notice package: @hopin/hugo-base-theme@0.0.6
npm notice === Tarball Contents === 
npm notice 1.0kB LICENSE                                           
npm notice 176B  build/layouts/_default/baseof.html                
npm notice 260B  build/layouts/partials/utils/google-analytics.html
npm notice 399B  build/layouts/partials/html/head.html             
npm notice 130B  build/layouts/_default/list.html                  
npm notice 1.2kB build/layouts/partials/utils/load-dev-assets.html 
npm notice 40B   build/layouts/_default/single.html                
npm notice 655B  package.json                                      
npm notice 983B  README.md                                         
npm notice 25B   build/theme.toml                                  
npm notice === Tarball Details === 
npm notice name:          @hopin/hugo-base-theme                  
npm notice version:       0.0.6                                   
npm notice package size:  2.7 kB                                  
npm notice unpacked size: 5.0 kB                                  
npm notice shasum:        6014a237a69eb0bde4e1112f1739049ae9ba4339
npm notice integrity:     sha512-MrdSQRcFEvLMs[...]+QK2L95sem66g==
npm notice total files:   10                                      
npm notice                                  
fatal: unable to access '***github.com/gauntface/hopin-base-theme.git/': Problem with the SSL CA cert (path? access rights?)
(node:11) UnhandledPromiseRejectionWarning: Error: Command failed: git push merge-release --tags
fatal: unable to access '***github.com/gauntface/hopin-base-theme.git/': Problem with the SSL CA cert (path? access rights?)

    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at exec (/github/home/.npm/_npx/11/lib/node_modules/merge-release/merge-release-run.js:53:44)
    at run (/github/home/.npm/_npx/11/lib/node_modules/merge-release/merge-release-run.js:63:3)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:11) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'm not entirely sure where the repo name is coming from but `***github.com/gauntface/hopin-base-theme.git/` looks off to me.

Any ideas what I'm doing wrong?

**Comment by mikeal** [comment]
This appears to have broken at some point, possibly because of a security change in GitHub Actions. I’ve logged an issue to try and resolve https://github.community/t5/GitHub-Actions/Cannot-push-tags-from-GitHub-Action/m-p/44878#M5958

**Comment by mikeal** [comment]
Fixed!
